category/urls.py
from django.urls import path, include
from .views import categories

app_name = 'category'

urlpatterns = [
    path('', categories, name='my_categories'),
]

profiles/urls.py
from django.urls import path
from .views import my_profile_view

app_name = 'profiles'

urlpatterns = [
    path('', my_profile_view, name='my_profile'),
]

todoapp/urls.py
from django.contrib import admin
from django.urls import path, include
from todolist.views import my_todos
from django.conf import settings
from django.conf.urls.static import static
from login_registration.views import login_view,logout_view, registerUserView
from .views import main

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', main, name='main'),
    path('home/', include('todolist.urls', namespace='TodoList')),
    path('my_profile/', include('profiles.urls', namespace='profiles')),
    path('my_categories/', include('category.urls', namespace='categories')),
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),
    path('register/', registerUserView, name='register'),
  ]

urlpatterns += static (settings.STATIC_URL, document_root = settings.STATIC_ROOT)
urlpatterns += static (settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

todolist/urls.py
from django.urls import path
from .views import my_todos

app_name = 'todolist'

urlpatterns = [
    path('', my_todos, name='my_todos'),
]

todoapp/views.py
from django.shortcuts import render

# Create your views here.
def main(request):
     context = {}
     return render(request, 'todoapp/mainpage.html', context)

templates/todoapp/base.html
{% load static %}
{% url 'login' as path_to_login %}
{% url 'main' as path_to_main_page %}
{% url 'register' as path_to_register_page %}
<!DOCTYPE html>
<html lang="en">
    <head>
      
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        
        <link rel="shortcut icon" href="{% static 'Logo.svg' %}" />

        <!-- Bootstrap CSS -->
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css" integrity="sha384-/Y6pD6FV/Vv2HJnA6t+vslU6fwYXjCFtcEpHbNJ0lyAFsXTsjBbfaDjzALeQsN6M" crossorigin="anonymous">
        <link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
        
       
        <link rel="stylesheet" type="text/css" href="{% static 'styles.css' %}">
        
        {% if request.path != path_to_main_page %}   
            {% if request.path != path_to_login %} 
                {% if request.path != path_to_register_page %} 
                     <script src="{% static 'sidebar.js' %}" defer></script>
                {% endif %}
            {% endif %}
         {% endif %}

        {% block scripts %}
        
        {% endblock scripts %}

        <title>TodoApp - {% block title %}{% endblock title %}</title>
    </head>
    <body class="">

        {% if request.path != path_to_main_page %}   
                    {% if request.path != path_to_login %} 
                        {% if request.path != path_to_register_page %} 
        <div class="wrapper">  

                        {% endif %}
                    {% endif %}
        {% endif %}
                <!--  the sidebar from not showing up on the main -->
                {% if request.path != path_to_main_page %}   
                    {% if request.path != path_to_login %} 
                        {% if request.path != path_to_register_page %} 
                            
                            {% include 'todoapp/sidebar.html' %}

                        {% endif %}
                    {% endif %}
                {% endif %}
              
                
                {% block content %}
                {% endblock content %}

        </div>

     
        <!-- Bootstrap js -->
        <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4" crossorigin="anonymous"></script>
        
    </body>
</html>

templates/todoapp/mainpage.html
{% extends "todoapp/base.html" %}

{% load static %}

{% block title %}
 Main
{% endblock title %}

{% block content %}


<div class="Home">

  <a class="brand-logo" href="{% url 'main' %}">
  <img class="logo" src="{% static 'Logo.svg' %}">
  <div class="brand-logo-name"><strong> ToDo </strong> </div>
  </a>


  <div class="call-to-action">
      <h1 class="title"> what to do  !</h1>
      <h3 class="subtitle"> <strong>ToDo</strong> IS TO ACHIEVE </h3>

      <a href="{% url 'login' %}" class="btn">Let’s get started</a>
  </div>

</div>

{% endblock content %}

templates/todoapp/sidebar.html
{% load static %}

{% url 'todolist:my_todos' as path_to_home %}
{% url 'category:my_categories' as path_to_categories %}
{% url 'profiles:my_profile' as path_to_my_profile %}
{% url 'login' as path_to_login %}
{% url 'main' as path_to_main_page %}


<div id="mySidebar" class="sidebar">
  <a href="javascript:void(0)" id="closebutton" class="closebtn">&times;</a>
  <div class="top-sidebar">
    <img src="{{request.user.profile.avatar.url}}" class="avatar-sm">&nbsp;{{request.user}}
  </div>
  
  <ul>
    <li><a class=" {% if request.path == path_to_home%}active{% endif %}" href="{{path_to_home}}"><i class="fa fa-home"></i>Home</a></li>
    <li><a class=" {% if request.path == path_to_categories%}active{% endif %}" href="{{path_to_categories}}"><i class="fa fa-tasks"></i>Task Management</a></li>
    <li><a class=" {% if request.path == path_to_my_profile%}active{% endif %}" href="{{path_to_my_profile}}"><i class="fa fa-user"></i>Profile</a></li>
    <li><a href="{% url 'logout' %}"><i class="fa fa-sign-out"></i>Logout</a></li>
  </ul> 
 

</div>